version: '3'
services:
  app:
    container_name: app
    restart: unless-stopped
    build: .
    ports:
      - '8090:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'