version: '3'
services:
  app:
    container_name: app
    restart: unless-stopped
    build: .
    ports:
      - '8090:8080'
    links:
      - mongo
    environment:
      - DB=test
      - DEBUG=true
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - '/data/db/:/data/db/'
    ports:
      - '127.0.0.1:27017:27017'