version: '3'
services:
  app:
    container_name: app
    restart: unless-stopped
    build: .
    ports:
      - '8090:8080'
    links:
      - mongo
    environment:
      - DB='mongodb://mongo:27017/test'
      - PORT=8080
      - DEBUG=true
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - '127.0.0.1:27017:27017'